---
# bibliography: references.bib
---

# Introduction {#intro}

This document is intended as both a general-purpose lab manual and a more detailed set of guidelines and suggestions related to open science principles, ethical research practices, and conscientious data management in the context of the kinds of research and data we most often deal with in this lab. The lab manual component lays out general information about the lab, our standard practices and guidelines, and what is expected of lab members in various roles. The latter part (from [Lab Practices](08-lab-practices.qmd#lab-practices) onward) goes into more detail and takes steps toward establishing formal lab policy around methodological transparency and data storage, preservation, and sharing, as well as some less prescriptive suggestions and points regarding issues I would encourage students to think critically about in their own work. This latter component is more so aimed at, and intended to be accessible to, early graduate students, but some parts may also be useful to honours students and other undergraduates curious about or considering pursuing research. 

See also our [lab webpage](https://onlineacademiccommunity.uvic.ca/lindsaylab/) for more information and (semi) current happenings.