---
# bibliography: references.bib
---

# Interested in joining the lab? {#joining}

Are you an undergraduate or graduate student interested in joining the lab? If so, treat this manual as a summary of how we conduct research and what you can expect if you join our team. The section on [Lab Philosophy and General Code of Conduct](https://e-y-m.github.io/lindsay-lab-manual/02-lab-philosophy.html) is a good big-picture place to start, and [Roles and Expectations](https://e-y-m.github.io/lindsay-lab-manual/04-roles.html) provides an overview of what kinds of activities lab members are involved in.

In terms of research topics and projects in the lab, I recommend checking out our [lab webpage](https://onlineacademiccommunity.uvic.ca/lindsaylab/), particularly the [Research](https://onlineacademiccommunity.uvic.ca/lindsaylab/research/) and [Publications](https://onlineacademiccommunity.uvic.ca/lindsaylab/publications/) pages, which provide overviews of ongoing/current/planned research lines.

If all that hasn't put you off, we welcome you to apply to our lab by contacting [me (Prof. Steve Lindsay)](mailto:slindsay@uvic.ca). For undergraduate students, we recommend having completed PSYC 201 (Research Methods in Psychology). Although UVic undergraduate students are given priority for RA positions, we have in the past brought on students from other institutions. 

If you are a prospective graduate student interested in applying to work with me, I recommend checking [UVic Psychology's portal for applicants](https://www.uvic.ca/socialsciences/psychology/graduate/future/index.php), which indicates whether or not I am currently accepting students (among other useful information). 

