---
# bibliography: references.bib
---

# Lab Philosophy and General Code of Conduct

This lab is subject to university-wide policies on [harassment and discrimination](https://www.uvic.ca/equity/discrimination-harassment/index.php) and [sexualized violence](https://www.uvic.ca/equity/sexualized-violence/policy-procedures/index.php). You are of course protected by, and expected to follow, these policies in all of your activities at UVic (and in many cases by law), but it is worth reiterating that they apply equally to all interactions related to your work in the lab, whether with other lab members or research participants. There will be zero tolerance for personal and sexual harassment, bullying, and discrimination on the basis of race, colour, ancestry, national origin, religion, sex, gender identity or expression, sexual orientation, age, physical or mental disability, marital or family status, and socioeconomic status. I also recognize that various forms of privilege have the effect of discouraging or preventing marginalized groups from participating in scientific research and pursuing careers in science. With this in mind, I aim to go beyond the bare minimum standard of avoiding the harms associated with harassment and discrimination and take active steps to make the lab and our work more inclusive and accessible. I am always open to critique and suggestions on how to improve current practices in this regard.

Treating research participants and their data ethically is paramount in the work we do. If you are working in the lab you are most likely already familiar with the basics of human research ethics from research methods and other courses, but if you need a refresher you may find parts of [this tutorial](http://www.pre.ethics.gc.ca/eng/education/tutorial-didacticiel/) helpful. Your particular responsibilities as far as implementing these principles will differ depending on your role in the lab, but it is important for all lab members to know the basics. Also under the data ethics umbrella is a goes-without-saying plea to never falsify or alter data to make it say something more “exciting”, or what you think I want it to say; it is a fact of research that our hypotheses will often be wrong, but truth is always more important than “success”.

I strongly value open and transparent research practices and this lab, like many others, is in a bit of a period of transition from the longstanding status quo – various methodological, analytic, and data management practices we now know to be suboptimal or downright wrong – toward how we know things should be done. Specific expectations on this theme for students conducting original research in this lab are outlined elsewhere in this document, but I hope all lab members will gain some exposure to the principles and practices of open science through working in the lab.

We also have other ethical duties as scientists: things like striving to make knowledge and the scientific process more accessible to the public; taking steps to make our discipline more inclusive, and amplifying the voices of the marginalized within it and taking their critiques seriously; considering the potential future implications of our research, for better or worse; and thinking critically about who our work – and the ways we conduct and present it – may be serving, harming, or leaving out. Most individual research projects are unlikely to dramatically change the world, but your potential positive influence is not limited to the details of the work you are involved in; just as valuable are the examples you set in how you conduct you work and your contributions to changing scientific culture (in this lab and beyond), which will require both small-scale and large-scale efforts. Systemic change is somewhat beyond the scope of a lab manual, but I encourage you to think critically about the smaller steps you can take in your own work toward making things better, and to feel free to discuss such issues with me if there are things you think we can do better as a group.

## Lab Meetings

All lab members will be expected to attend weekly lab meetings if you are available at the scheduled time. Accommodating graduate and honours students’ schedules will take priority in determining lab meeting times, so it may not always be possible to accommodate all research assistants’ schedules as well. RAs who have a scheduling conflict will generally be expected to meet or check in informally with your project group/student supervisor on a weekly basis or as agreed. If you usually attend lab meetings but can’t make it on a particular day, I appreciate advance notice if possible so I know who to expect and can cancel meetings if enough people are unavailable that it does not seem worthwhile to hold a meeting. 

Lab meetings are usually fairly informal and are an opportunity for everyone to get up to date on the progress of various projects, collaboratively solve issues that come up in the course of data collection or other parts of the research process, and discuss results as they come in. Some lab meetings may be reserved for training opportunities, discussing important topics (e.g., related to open science), or for lab members to present their research findings or practice for an upcoming presentation. Graduate and honours students will typically give at least one presentation per year in lab meeting, but all lab members are welcome to take advantage of this opportunity to practice and get feedback on presentations in a friendly, supportive environment. If you are interested in doing so, please get in touch with me and I will try to reserve time for you.

