---
# bibliography: references.bib
---

# Lab Spaces and Resources

## Lab Rooms

The lab’s graduate student office is located in Cornett A193 and has desk room and desktop PCs with 2 monitors for three students. Currently only two of these are occupied, so the third is available for use by honours students and research assistants on a drop-in basis as long as the room is open. Please do not install software on lab computers without express permission from Prof. Lindsay or the Lab Manager.

We have two individual participant testing rooms, each with a desktop PC and a single monitor, located in Cornett A178 and A179. Both are equipped to run experiments using E-Prime software. These rooms are also available for student use when they are not occupied for the purpose of participant testing. Reserving these rooms for either purpose is done through a shared Google Calendar, which you will be given access to as needed or upon request. 

The CaBS department meeting room, Cornett A069, is most often used for lab meetings but is available for other purposes (e.g., holding tutorials or training sessions, practicing presentations, etc.). Reservations are made through a shared Google Calendar that I have ongoing access to, and CaBS graduate students can request personal access from the administrator (currently also [me](mailto:slindsay@uvic.ca)). 

## UVic testing spaces

In recent years we have shifted toward testing undergraduate participants in groups for some projects, which requires reserving computer lab space in the Clearihue or Human and Social Development (HSD) buildings. Schedules for these labs can be viewed [here](https://www.uvic.ca/systems/facilities/classroomdetails/index.php). Postdoctoral fellows, graduate students, and honours students working in the lab may request to reserve these labs for up to 6 hours/week once ethics approval has been obtained for a project. Note that the current booking system (“Non-academic bookings” at [this link](https://www.uvic.ca/systems/labs/booking-space/teaching-lab-booking/index.php)) requires a login from an account with employee (e.g., RA/TA) status.

Booking requests and changes associated with the same project should all be made by the same person (e.g., a graduate student will typically coordinate their own bookings along with those of any research assistants working on their projects), and it is important these reservations be cancelled with as much notice as possible if you do not plan to use the room. Once rooms are booked, timeslots on SONA will need to be set up. Although this will typically be handled by the supervising graduate student or lab manager, you may be involved in setting up studies and timeslots on SONA. [This guide](https://www.uvic.ca/socialsciences/psychology/research/participants/index.php) includes comprehensive information on how to do so.

For online experiments, we typically collect data via Prolific.co, a crowdsourcing platform where online workers complete experiments and other tasks for compensation. Dr. Lindsay has funds to support such online data collection. See [this page](https://researcher-help.prolific.co/hc/en-gb/articles/360009220953-Setting-up-a-study-on-Prolific-step-by-step-guide-) for information on how to create a study on Prolific.


## Lab Software

We currently have two active licences for the experiment development and administration software E-Prime (one for version 2 and one for version 3). These licenses are in the form of USB keys that can be used on any lab computers with E-Prime installed and are usually stored in the graduate student office. University Systems has a number of E-Prime licenses that allow for experiment administration only and can install the program in a single computer lab (20-25 people), usually one of HSD A150, A160, or A170, upon request.

For running online experiments, the lab also has access to a Qualtrics Survey Software license. See [this site](http://sites.cognitivescience.co/qualtrics/building-a-psychology-experiment) for useful tutorials on designing Qualtrics surveys and experiments for psychological research.

In recent years, we have also begun using freely available [PsychoPy](https://www.psychopy.org/) to design experiments in Python (which can then be administered online via [Pavlovia](https://pavlovia.org/) for a small per-participant cost). See [this site](https://psychopy.org/gettingStarted.html) for helpful information and tutorials.

In terms of statistical analysis software, the lab does not have a licence for SPSS. We attempt to keep the freely available [JASP](https://jasp-stats.org/) and [R/RStudio](https://posit.co/products/open-source/rstudio/) up to date on lab computers and recommend that students use these programs for analyses when appropriate. JASP offers an easy-to-use GUI similar to SPSS, while R/RStudio requires coding but has much more flexibility.