---
# bibliography: references.bib
---

# Roles and Expectations

Typically, the lab team consists of one to three graduate students, several part-time paid Research Assistants (usually but not always undergrads), and a few PSYC undergrads doing an independent studies course (PSYC 390 or PSYC 490) or an honours thesis under my supervision.  

## Research Assistants

Paid undergraduate research assistants (RAs) typically start at $18/hour. Research assistants (RAs) are most often involved in scheduling and testing undergraduate research participants (for an example of what a typical in-person testing session might look like see [this section](https://e-y-m.github.io/lindsay-lab-manual/08-lab-practices.html#example-session)), but sometimes work on other tasks such as data entry, transcription, developing stimulus sets, and programming experiments. 

I want all RAs to have a rewarding and educational experience in the lab. If you are not getting what you hoped out of your experience, please talk to me so that we can try to find work and training opportunities more in line with your goals or, if that is not possible, point you toward other labs that might be a better fit.

Undergraduate students working the lab in the context of PSYC 390, 490 (Independent Study), or 499 (Honours) should have received clear written specification of course requirements and criteria. If in doubt, please ask. Such students typically are not paid for working on their research projects.

### Hours and scheduling

RAs are typically expected to be able to commit to around 6 hours/week of lab work on average (including weekly lab meetings, other meetings related to lab projects, and training sessions), although the availability of hours will vary substantially over the course of the semester depending on lab needs. It is important to note that the estimate hours is an average. There may be some weeks where there is little/no work and some weeks (e.g., during peak SONA data collection periods near the beginning and end of the semester, or near to conferences) where there will be more work. But, scheduling for most projects is highly flexible and you do not need to commit to working the same hours every week. If there are weeks you are particularly busy with midterms or other commitments, it is perfectly fine to take those weeks off from lab work entirely.

Projects run in the lab's individual testing rooms (Cornett A178 and A179) will require you to book space on the lab's Google Calendar. These rooms are kept locked so if you are working on a project that requires access we will request the department assign you a key that opens both rooms as well as the external door (A177), which will require you to bring ID and a \$5 deposit (that will be returned when you return the key at the end of the semester) to the Psychology main office.

If you are working on a project that requires booking computer lab space, you will typically request space through the graduate or honours student in charge of that project. If you need to cancel or modify a requested booking it is very important to let this person know as soon as possible.

### RA Onboarding

The general onboarding process/checklist for new RAs is as follows:

-   Read and familiarize yourself with the following manual sections: [Lab Philosophy and General Code of Conduct](https://e-y-m.github.io/lindsay-lab-manual/02-lab-philosophy.html), this section, [Roles and Expectations](https://e-y-m.github.io/lindsay-lab-manual/04-roles.html), [Communication](https://e-y-m.github.io/lindsay-lab-manual/05-communication.html), and [Lab Spaces and Resources](https://e-y-m.github.io/lindsay-lab-manual/03-lab-resources.html)

-   If you will be taking on a paid position, fill out a [new hire form](https://www.uvic.ca/vpfo/financial-services/assets/docs/payroll/Resources/dept-web-time-entry/new-rehire-form-web-time-entry.pdf) (Note that you may need to login with your UVic account to access this form). This form may also be provided to you by the lab manager or supervising graduate student. For information on how to enter your worked hours for approval, see [this link](https://www.uvic.ca/vpfo/financial-services//resources/payroll/employee-dashboard/entering-your-timesheet.php).

-   Prior to conducting any research with human subjects, ensure that you have completed the [Tri-Council Policy Statement (TCPS-2 CORE) ethical certification course](https://tcps2core.ca/welcome). Although this course is fairly comprehensive, I also highly recommend reviewing our own guidelines and recommendations for research ethics [here](https://e-y-m.github.io/lindsay-lab-manual/08-lab-practices.html#human-research-ethics).

-   Meet with me and/or graduate students in the lab to determine which project(s) you would like to be involved in and in what capacity you will be involved in those projects

-   Prior to running (or co-running) any study sessions, sit in on *at least two* study sessions run by another RA or graduate student

-   Prior to running any study sessions by yourself, complete *at least one* "practice session" where you are supervised by another project RA or graduate student

### Research and Scientific Ethics

As a research assistant you will probably not be involved with ensuring the project you are working on adheres to ethical guidelines, but you will be responsible for putting these principles into practice by ensuring research participants are treated ethically and that any data you have access to or are involved in analyzing are handled properly. If you will be working with participants recruited through UVic's SONA system, you will be expected to be familiar with the [current guidelines](https://www.uvic.ca/socialsciences/psychology/research/participants/index.php) regarding use of this system and under what circumstances participants should receive credit, be marked as excused, or be penalized for not showing up for a session.

#### Research Participants

If you are involved in testing research participants, your ethical duties will include ensuring (1) informed and ongoing consent, (2) the educational value of participation, by providing verbal or written debriefing at the end of the experiment, and (3) a positive overall experience with research participation, by treating participants fairly and kindly (within reason). You will receive additional training on these expectations before you start testing, and will be required to complete the [Tri-Council Policy Statement (TCPS-2 CORE) ethical certification course](https://tcps2core.ca/welcome), but I will review some basics here.

The informed consent process will usually take the form of a screen at the beginning of the experiment that participants are required to read and sign/acknowledge. Not all potential participants read this as carefully as they should, but you should do what you can to ensure this within reason (e.g., if someone turns the sheet over and signs it as soon as you hand it to them, you should politely request they take time to read it). You should be familiar with the contents of the consent form and discuss any parts you have questions about with your project supervisor so that you are prepared to address questions prospective participants might have.

All participants who complete or get partway through a study should be debriefed regarding the purpose of the research. We usually do this verbally, based on previous experience suggesting written debriefing documents tend to go to waste. In this case you will likely receive a script for reference. If it is not possible to deliver a verbal debriefing -- e.g., if a session goes over the scheduled time, a participant has to leave quickly, or extenuating circumstances require you to terminate a session early -- you should make sure all participants receive this information by email, either by doing so yourself or by letting your project supervisor know.

Finally, it is important to treat participants with standard professionalism and politeness (within limits), even if they do not always do the same. This means being patient with participants when they are a few minutes late, seem not to be paying much attention, or otherwise inconveniencing you; taking an approach of reasonable leniency in deciding whether or not to penalize no-shows or latecomers who could, by the rules, be penalized; and always thanking everyone for their participation at the end. This does not mean that the participant is always right; providing you act within PRPS rules in applying penalties you are not obligated to give in to participant demands that you reverse such penalties, nor are you expected to put up with yelling, harassment, or otherwise disruptive/threatening behaviour. Although we do not expect such behaviour to occur, you are always entitled to terminate a session under such circumstances.

#### Confidentiality and data ethics

RAs involved in data collection will at the very least have access to participant names and contact information, and, for some projects, may also have access to other sensitive information. It is important to treat this information with appropriate care. Participants consent under the assumption of anonymity and confidentiality, which most obviously means we agree not to share any data that can be traced back to them, but also means you should not discuss individual research participants or their data with anyone outside the lab (even simply to disclose that they participated). Additionally, you must not abuse your access to participant contact information to contact anyone for reasons unrelated to their research participation. Paperwork containing participant names is typically stored securely on lab premises but if you are working on a project that requires you to keep such information on your person, or accidentally take it with you, please be very careful to store it securely.

As for electronically stored data, such as that generated by experimental software, you should **never** delete or alter raw data files for any purpose. Even if something occurs that you know will require excluding the file from later analyses, such as a computer glitch partway through, or you realize you have accidentally assigned someone the wrong participant number, you should leave the file itself as is and note the issue on the anonymized record sheet provided by your direct supervisor next to the appropriate participant number. Also, in this lab we are more interested in scientific truth than success; accordingly, you should **never** try to falsify or alter data, or encourage participants to respond in a certain way, in hopes of making results turn out the way we might want them to.

## Honours Students

Honours students will take the lead on an independent research project with my guidance, and sometimes that of a graduate student co-supervisor. Most often, this takes the form of a start-to-finish study for which you collect your own data (sometimes with RA assistance), but analytically-focused projects using already existing data from our lab or elsewhere are also possible.

For projects that require data collection, it is important we settle on a topic early in the fall semester (ideally sometime in the summer beforehand) so things can get going as soon as possible. I will usually have a few project suggestions in mind but am open to discussion with the goal of finding a mutually beneficial project that both has some elements that interest you and fits well with lab standards and expertise.

General expectations regarding communication and ethics discussed in the previous section also apply to honours students. If your project requires a new HREB application you will be more involved in the planning stage of research ethics than RAs, but this will be a collaborative effort and you will receive guidance throughout this process.

In addition to attending lab meetings, honours students will also meet with me (and, if applicable, others working on the same project) on a weekly basis for progress updates, to work out any problems that arise. Students will be expected to keep a record of notes from weekly meetings, which they send to me afterwards (ideally within 24 hours). This helps detect misunderstandings and also provides a record that we can later consult if the need arises. 

As part of these meetings, we will also discuss the research literature relevant to your project. Usually I will provide some relevant readings at the beginning of your project as a starting point and may have additional suggestions as the project proceeds, but you are also encouraged to branch out and start exploring the literature on your own. You will be expected to maintain an [annotated bibliography](https://www.lib.sfu.ca/help/cite-write/citation-style-guides/annotated-bibliography) throughout the course of your honours year, and I will provide you with feedback on this document and more general advice aimed at improving your skills in efficiently reading and evaluating scientific literature.

Regarding the thesis itself, we will set informal, section-by-section writing deadlines throughout the year in line with those recommended by the honours coordinator. I will provide feedback on draft sections as you complete them.

Compared to RAs, honours students are more likely to be dealing directly with data. As such, you will also be subject to certain expectations regarding good data management and thorough documentation. You will also be expected, time permitting, to pre-register your research plan. Some information and guidelines related to these expectations are available in the Lab Practices section of this document, but you will receive further guidance as your project proceeds.

## Graduate Students

In general, the graduate student experience in the Lindsay Lab can vary from student to student and project to project, with a fair amount of flexibility. The aim of this section is to provide a broad framework that is likely to apply to most graduate students. Much of the specific expectations will be determined in initial meetings with me and updated throughout your degree as necessary. For current department- and program-level guidelines, resources, and expectations at UVic, we highly recommend checking out the [UVic Psychology Graduate Training Handbook](https://www.uvic.ca/socialsciences/psychology/assets/docs/current/gradRegs.pdf)

Graduate students working in the lab are generally not paid for working on their research projects. They may be supported by a stipend, but that is not considered payment for services. Graduate students with questions regarding expectations are encouraged to review [this document](https://onlineacademiccommunity.uvic.ca/lindsaylab/wp-content/uploads/sites/4861/2020/07/Goals-for-Academia-2018.pdf) and to speak with me regarding any questions, concerns, or suggestions.

### MSc

Although topics chosen by MSc students vary, students will general adapt an ongoing research line in the lab for their Master's Thesis. The aforementioned Graduate Training Handbook has several sections that provide guidance on the thesis (e.g., committees, thesis format, oral examination). For examples of recent MSc theses from the lab, see:

[Dr. Mario Baldassari: Predicting Lineup Identifications](https://dspace.library.uvic.ca/handle/1828/8909)

[Dr. Kaitlyn Fallow: Characterizing the Materials-Based Bias Effect: A Robust yet Mysterious Conservative Response Bias in Recognition Memory for Paintings](https://dspace.library.uvic.ca/handle/1828/5830)

[Eric Mah: Improving Lineup Effectiveness through manipulation of eyewitness judgment strategies](https://dspace.library.uvic.ca/handle/1828/11968)

These will give you a general idea of the typical scope and depth of theses in the lab.

### PhD

Dissertations will often follow naturally from the thesis in terms of topic, and typically involve 2-3 manuscripts worth of empirical and theoretical work. Dissertations most often follow the 'five-chapter' format, but can also follow the 'three-article' or 'manuscript-style' format. Again, a fair amount of flexibility. For examples of lab dissertations, see:

[Dr. Mario Baldassari: Two approaches to assessing eyewitness accuracy](https://dspace.library.uvic.ca/handle/1828/8909)

[Dr. Kaitlyn Fallow: Test position effects on recognition memory for pictures and words](https://dspace.library.uvic.ca/handle/1828/13463)

Alongside the dissertation, students in the department must complete *candidacy exams,* which comprise a *major* and *minor* component. These have historically been *exams* in name only, and more typically take the form of projects that allow students to demonstrate core competencies in research, theory, and methods. In fact, the original form of this lab manual was Dr. Kaitlyn Fallow's major candidacy. Other examples of major and minor exams include comprehensive literature reviews (that may later be directly incorporated into the dissertation itself) or development of code/programs. There is a lot of flexibility in terms of what students can do for their candidacy exams.

### Communication

The frequency of student-supervisor communication will vary as a function of student need and supervisor availability. For students starting out, there will typically be weekly meetings (Zoom or in-person) to discuss progress and updates. For students later in their degree, meetings may be less frequent and scheduled based on need. Regardless of meeting frequency, graduate students are expected to maintain regular email communication re:ongoing projects and relevant updates.

### Coursework and TA-ing

Coursework requirements for MSc/PhD students in the Cognition & Brain Sciences program at UVic are relatively light, and typically consist of a handful of statistics courses, independent study/research apprenticeships (which usually take the form of a semester-long project or targeted seminar with another faculty member in the department), higher-level seminar courses, and regular enrollment in the [Cognition and Brain Sciences Seminar](https://www.uvic.ca/socialsciences/psychology/graduate/brain-sciences/cabssem/index.php), a weekly seminar series where department students, faculty, and invited guests present on their research. See the [department page](https://www.uvic.ca/socialsciences/psychology/graduate/brain-sciences/index.php) for specific MSc/PhD course requirements.

Almost all graduate students in the lab take on teaching assistantships (TAs). These are a valuable means of gaining teaching experiences and a source of graduate student funding, but it is up to the student as to how many TA positions they wish to take on during the course of their degree. Students highly interested in academic teaching positions might TA the majority of semesters. There are also opportunities for students (typically PhD) to teach courses in the department.

### Professional Development

Outside of academic skill development, graduate students are encouraged to consider professional development opportunities. Participation in department- or university-level organizations is one avenue for such opportunities. For example, students in the Lindsay Lab have been fruitfully involved with departmental organizations such as the [Psychology Graduate Student Council](https://onlineacademiccommunity.uvic.ca/pgsc/) and the [Equity, Diversity, and Inclusion Committee](https://www.uvic.ca/socialsciences/psychology/home/diversity/index.php). Involvement in these organizations is a great way to get involved in and make contributions to the department (and build your CV).

Although no current/past graduate students have taken on co-op work, UVic has provisions in place for [interested graduate students](https://www.uvic.ca/coop/info-for/graduate-students/index.php). Co-op positions may be especially worthwhile for those considering careers outside academia (see this [APS post](https://www.psychologicalscience.org/observer/careers-outside-academia-webinar) for examples). Students will typically discuss professional development goals in initial meetings with me, and revisit these goals throughout the degree.