---
# bibliography: references.bib
---

# Funding

Most general funding issues (e.g., graduate student fellowships, payment rates for research assistantships and work-study postings) will have been discussed and negotiated prior to your arrival in the lab.

My capacity to fund travel expenses for conferences or workshops, purchase equipment and software to make your research easier or enable new projects, and cover registration fees for societies, courses, or certificates relevant to your research or professional development will vary depending on the expense and current grant funding. I cannot guarantee funding for these things beyond what was negotiated prior to your arrival, but if there is something that would be helpful for you to have or attend I encourage you to ask. You will never be expected to fund expenses *necessary* for your research out of your own pocket. If you must make a research- or lab-related purchase yourself, you should fill out a [Business Expense Reimbursement Claim](https://www.uvic.ca/vpfo/financial-services/assets/docs/acctpayable/BER.pdf) and send it to Steve or your supervising graduate student. I will always cover expenses related to printing or copying necessary paperwork, paid room rentals (if required), etc.

## Conferences and workshops

With respect to travel expenses in particular, all graduate students are eligible to apply for travel grants offered by the UVic [Faculty of Graduate Studies/Graduate Students’ Society](https://www.uvic.ca/graduatestudies/finances/financialaid/travel/), and students currently working as Teaching Assistants are also eligible to apply for funding through [CUPE 4163](https://4163.cupe.ca/resources/component-1/) Component 1 (see the section titled “Conference Fund”). Many professional societies also offer general or conference-specific travel funding opportunities for member and/or presenters. Both graduate and undergraduate students who are members of [Psi Chi](https://www.psichi.org/page/awards) may be eligible for their travel awards as well.

I will cover the costs of professional poster printing for conferences at UVic or elsewhere for lab members at any level who are interested in presenting. UVic’s Psi Chi Chapter hosts an excellent annual undergraduate research conference called [Making Waves](https://uvicmakingwaves.weebly.com/) that honours students are usually required to present at, and undergraduate research assistants are strongly encouraged to consider doing so as well. It is a very friendly, low-stress introduction to conference presentations, and you can present on research or analyses you have done in the lab, as part of a class, or even a research proposal.

Another excellent yet low-key local-ish conference members of this lab often attend and/or present at is [NOWCAM](https://onlineacademiccommunity.uvic.ca/NOWCAM-conference/), which is held in mid-May and aims to showcase graduate and undergraduate student research. When NOWCAM is held locally (i.e., Victoria or the Lower Mainland) all students are especially encouraged to apply to present (and undergraduates who have already presented at Making Waves can apply to present the same poster). Although less commonly attended by lab members than NOWCAM, [Connecting Minds](https://connectingminds.wildapricot.org/) is another great annual undergraduate research conference hosted by Kwantlen Polytechnic University on the Lower Mainland.
