---
# bibliography: references.bib
---

# References

Button, K. S., Ioannidis, J. P. a, Mokrysz, C., Nosek, B. a, Flint, J., Robinson, E. S. J., & Munafò, M. R. (2013). Power failure: why small sample size undermines the reliability of neuroscience. *Nature Reviews: Neuroscience*, *14*(5), 365--76.

Canadian Institutes of Health Research, Natural Sciences and Engineering Research Council of Canada, & Social Sciences and Humanities Research Council of Canada. (2014). *Tri-Council Policy Statement: Ethical conduct for research involving humans*.

Cohen, J. (1962). The statistical power of abnormal-social psychological research: A review. *The Journal of Abnormal and Social Psychology*, *65*(3), 145--153. http://doi.org/10.1037/h0045186

Collaboration, O. S. (2015). Estimating the reproducibility of psychological science. *Science*, *349*(6251), aac4716-aac4716. http://doi.org/10.1126/science.aac4716

de Leeuw, J. R. (2015). jsPsych: A JavaScript library for creating behavioral experiments in a Web browser. *Behavior Research Methods*, *47*(1), 1--12. http://doi.org/10.3758/s13428-014-0458-y

Difallah, D., Filatova, E., & Ipeirotis, P. (2018). Demographics and Dynamics of Mechanical Turk Workers. *Proceedings of the Eleventh ACM International Conference on Web Search and Data Mining  - WSDM \'18*, (August), 135--143. http://doi.org/10.1145/3159652.3159661

Hara, K., Adams, A., Milland, K., Savage, S., Callison-Burch, C., & Bigham, J. P. (2018). A Data-Driven Analysis of Workers\' Earnings on Amazon Mechanical Turk. *Proceedings of the 2018 CHI Conference on Human Factors in Computing Systems  - CHI \'18*, 1--14. http://doi.org/10.1145/3173574.3174023

Henrich, J., Heine, S. J., & Norenzayan, A. (2010). The weirdest people in the world? *Behavioral and Brain Sciences*, *33*(2--3), 61--83. http://doi.org/10.1017/S0140525X0999152X

Hoekstra, R., Morey, R. D., Rouder, J. N., & Wagenmakers, E. J. (2014). Robust misinterpretation of confidence intervals. *Psychonomic Bulletin and Review*, *21*(5), 1157--1164. http://doi.org/10.3758/s13423-013-0572-3

Ioannidis, J. P. A. (2005). Why most published research findings are false. *PLoS Medicine*.

Ipeirotis, P. G. (2010). Analyzing the Amazon Mechanical Turk marketplace. *XRDS: Crossroads, The ACM Magazine for Students*, *17*(2), 16. http://doi.org/10.1145/1869086.1869094

Kerr, N. L. (1998). HARKing: Hypothesizing After the Results are Known. *Personality and Social Psychology Review*, *2*(3), 196--217. http://doi.org/10.1207/s15327957pspr0203_4

Lakens, D. (2014). Performing high-powered studies efficiently with sequential analyses. *European Journal of Social Psychology*, *44*(7), 701--710. http://doi.org/10.1002/ejsp.2023

Lakens, D. (2017). Equivalence Tests: A Practical Primer for t Tests, Correlations, and Meta-Analyses. *Social Psychological and Personality Science*, *8*(4), 355--362. http://doi.org/10.1177/1948550617697177

Lindsay, D. S., Simons, D. J., & Lilienfeld, S. O. (2016). Research Preregistration 101. *Observer*.

Nosek, B. A., & Bar-Anan, Y. (2012). Scientific Utopia: I. Opening Scientific Communication. *Psychological Inquiry*, *23*(3), 217--243. http://doi.org/10.1080/1047840X.2012.692215

Nosek, B. A., Spies, J. R., & Motyl, M. (2012). Scientific Utopia: II. Restructuring Incentives and Practices to Promote Truth Over Publishability. *Perspectives on Psychological Science*, *7*(6), 615--631. http://doi.org/10.1177/1745691612459058

Pittman, M., & Sheehan, K. (2016). Amazon's mechanical turk a digital sweatshop? Transparency and accountability in crowdsourced online research. *Journal of Media Ethics: Exploring Questions of Media Morality*, *31*(4), 260--262. http://doi.org/10.1080/23736992.2016.1228811

Poushter, J. (2016). *Smartphone Ownership and Internet Usage Continues to Climb in Emerging Economies*. *Pew Research Center*. http://doi.org/10.1017/CBO9781107415324.004

Ross, J., Zaldivar, A., Irani, L., & Tomlinson, B. (2010). Who are the Turkers? Worker Demographics in Amazon Mechanical Turk. *Chi Ea 2010*, (July 2016), 2863--2872. http://doi.org/10.1145/1753846.1753873

Rouder, J. N. (2014). Optional stopping: no problem for Bayesians. *Psychonomic Bulletin & Review*, *21*(2), 301--308. http://doi.org/10.3758/s13423-014-0595-4

Rouder, J. N. (2016). The what, why, and how of born-open data. *Behavior Research Methods*, *48*(3), 1062--1069. http://doi.org/10.3758/s13428-015-0630-z

Simmons, J. P., Nelson, L. D., & Simonsohn, U. (2011). False-positive psychology: Undisclosed flexibility in data collection and analysis allows presenting anything as significant. *Psychological Science*, *22*(11), 1359--1366. http://doi.org/10.1177/0956797611417632

Smith, A. (2016). *Gig Work, Online Selling and Home Sharing*.

Society for the Improvement of Psychological Science. (n.d.). Retrieved June 19, 2018, from https://improvingpsych.org/

van \'t Veer, A. E., & Giner-Sorolla, R. (2016). Pre-registration in social psychology---A discussion and suggested template. *Journal of Experimental Social Psychology*. http://doi.org/10.1016/j.jesp.2016.03.004

Vankov, I., Bowers, J., & Munafò, M. R. (2014). On the persistence of low power in psychological science. *Quarterly Journal of Experimental Psychology*, *67*(5), 1037--1040. http://doi.org/10.1080/17470218.2014.885986

Velicer, W. F., Cumming, G., Fava, J. L., Rossi, J. S., Prochaska, J. O., & Johnson, J. (2008). Theory Testing Using Quantitative Predictions of Effect Size. *Applied Psychology*, *57*(4), 589--608. http://doi.org/10.1111/j.1464-0597.2008.00348.x
